### ISSUE TITLE
内部嵌套的recycler布局稍微复杂点，数据量很大上下滑动很卡

### ISSUE THREAD

**Issue by LgSecret** [Jeromeer/HorizontalScrollDemo-master#7]
大佬求助 ！！  去掉嵌套的HorizontalScrollView之后内部的recycleview如何多条联动，如何联动上方的HorizontalScrollView 头部

**Comment by Jeromeer** [comment]
为什么要去掉呢?数据量大 是横向的数据量还是垂直方向的?垂直方向上的,我这边测试过线上项目,可以显示2000+条 纵享丝滑,横向上,因为嵌套了HorizontalScrollView会导致RecyclerView的缓存策略失效,所以不建议横向滑动填充过多数据
